"""empty message

Revision ID: fc63627fad78
Revises: 4a9f8c2e1b3d
Create Date: 2026-04-18 16:22:52.971779

"""
import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa
import app.models


# revision identifiers, used by Alembic.
revision = 'fc63627fad78'
down_revision = '4a9f8c2e1b3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alias', sa.Column('expiry_action', app.models.IntEnumType(app.models.AliasExpiryAction), server_default='0', nullable=True))
    op.add_column('alias', sa.Column('expiry_date', sqlalchemy_utils.types.arrow.ArrowType(), nullable=True))
    op.add_column('alias', sa.Column('expiry_notify_user', sa.Boolean(), server_default='0', nullable=True))
    op.create_index('ix_alias_expiry_date', 'alias', ['expiry_date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_alias_expiry_date', table_name='alias')
    op.drop_column('alias', 'expiry_notify_user')
    op.drop_column('alias', 'expiry_date')
    op.drop_column('alias', 'expiry_action')
    # ### end Alembic commands ###
